
context.create.after.exception = Some error [{0}] when creating context
context.create.after.success   = Context [{0}] successfully created
context.create.before          = Try to create new context...
